config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :relationships, only: [:create, :destroy]
  
  resources :posts do
    resources :comments 
    member do
    put 'Yes' => 'posts#upvote'
    put 'No' => 'posts#downvote'
   end
end

resources :posts do
end

resources :votes, only: [] do
  get 'up', on: :collection
  get 'down', on: :collection
end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  # Define Root URL  root 'pages#index'
  root 'pages#index'
  
   # Define Routes for Pages
   get '/home' => 'pages#home' # override default routes.
   get '/user/:id' => 'pages#profile'
   get '/explore' => 'pages#explore'
   get '/show' => 'pages#show'
   
  namespace :charts do 
    get "votes"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  acts_as_votable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post, only: [:upvote, :downvote, :destroy, :create, :edit, :update]
    before_action :find_comment, only: [:destroy, :update, :edit, :comment_owner ]
    before_action :comment_owner, only: [:destroy, :edit, :update]
     
    def new
        
    end 

    def create
      @comment = @post.comments.create(params[:comment].permit(:content))
      @comment.user_id = current_user.id
      @comment.save
      
      if @comment.save
          redirect_back(fallback_location: root_path)
      else
          render 'new'
      end
  end

  def destroy
     @comment.destroy
     redirect_back(fallback_location: root_path)
  end

  def edit
      @comment = Comment.find(params[:id])
      @p = Post.find(params[:post_id])
  end

  def upvote     
    @comment = Comment.find(params[:id])
    @comment.upvote_from current_user
    redirect_back(fallback_location: root_path)
end

def downvote
    @comment = Comment.find(params[:id])
    @comment.downvote_from current_user
    redirect_back(fallback_location: root_path)
end

  def update
    if @comment.update(params[:comment].permit(:content))
      respond_to do |f|
          if (@comment.save) 
              f.html { redirect_to "", notice: "Comment edited!" }
          elsif
              f.html { redirect_to "", notice: "Error: Your Comment is the same!." }
         else
             render 'edit'
      #f.html { render 'edit'} ## Specify the format in which you are rendering "new" page      
          end
       end
      end
  end
 


  private

  def find_post
      @post = Post.find(params[:post_id])
  end

  def find_comment
      @comment = @post.comments.find(params[:id])      
  end

  def comment_owner
      unless current_user.id == @comment.user_id
          flash[:notice] = "You can't do that!"
          redirect_back(fallback_location: root_path)
      end
  end
  

end

app/helpers/comments_helper.rb
module CommentsHelper
   
end

app/views/comments/_comment.html.erb
<% @p.comments.each do |comment| %>
 <span><%= comment.user_id %></span>
 <div><%= comment.content %></div>
 <div><%= comment.created_at %></div>

 <% if comment.present? == !nil %>
     <%= link_to up_votes_path(object:'Comment', id:comment.id) do %>
       <i class="fa fa-thumbs-up" aria-hidden="true">Like</i>
       <%= comment.get_upvotes.size %>
     <% end %>
     <%= link_to down_votes_path(object:'Comment', id:comment.id) do  %>
       <i class="fa fa-thumbs-down" aria-hidden="true">Dislike</i>
       <%= comment.get_downvotes.size %>
     <% end %>
  <% end %>


    <% if current_user == comment.user %> 
      <%= link_to "Delete",[comment.post, comment], method: :delete, data: {confirm: "Are you sure?"} %>
      <%= link_to "Edit",edit_post_comment_path(comment.post, comment) unless comment.new_record? %> 
   <% end %>
 
  <hr>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@p, @p.comments.build])  do |f| %> 

  <p><%= f.text_area :content %></p>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<%= form_for([@post, @comment]) do |f| %>
  <p><%= f.text_area :content %></p>
  <%= f.submit %>
<% end %>